#!/bin/sh
docker run \
    --rm \
    -i \
    --network=host \
    -v "$HOME":"$HOME": \
    -v "$PWD":"$PWD": \
    -u $(id -u) \
    -w "$PWD" \
    php:7-alpine \
    php "$@"

exit $?


# ~/bin/php-vscode 
